### PR TITLE
FIX Query now accepts field types array and will cast numeric fields as text

### LINKED ISSUE #176: Cannot perform a string filter on a numeric field
Steps:

* Enable a data column in the results view that is "numeric" type
* Ensure one or more filters is set to "all columns"
* Try to filter by "foo" on the frontend

Error from CKAN:

```
operator does not exist: numeric ~* unknown
```

We probably need to cast all fields as strings when performing ILIKE checks

### PR DESCRIPTION
**Pull request by robbieaverill**
Resolves #176

### CODE REVIEW

File: client/src/lib/CKANApi/DataStore/Query.js [hunk 1]
```diff
@@ -232,7 +232,7 @@ class Query {
           const edgeMatch = strict ? '' : '%';
           const matchType = match ? 'ILIKE' : 'NOT ILIKE';
 
-          return `"${queryColumn}" ${matchType} '${edgeMatch}${queryTerm}${edgeMatch}'`;
+          return `CAST("${queryColumn}" AS TEXT) ${matchType} '${edgeMatch}${queryTerm}${edgeMatch}'`;
```
Comment (ScopeyNZ) [inline client/src/lib/CKANApi/DataStore/Query.js]: This can really negatively affect performance. Casts happen for every row and indexes are not adhered to. Can we somehow leverage the fact we get (and store) the column data type from CKAN?

Comment (robbieaverill) [reply client/src/lib/CKANApi/DataStore/Query.js]: Sure, let me have a look tomorrow

**Comment by robbieaverill** [comment]
I've updated this so that now the Query class accepts an array of field type definitions, and will cast numeric fields as text during query parsing. This is a breaking change, but since we're in beta I think it's OK at the moment.

File: client/src/lib/CKANApi/DataStore/Query.js [hunk 2]
```diff
@@ -227,12 +229,18 @@ class Query {
       ? ` WHERE (${this.filterBundles.map(bundle =>
         // Map those bundles - set "column" ILIKE '%field%' (and escape single quotes)
         bundle.map(({ column, term, strict, match }) => {
-          const queryColumn = column.replace('"', '""');
+          const columnName = column.replace('"', '""');
+          // Check for defined field types, and perform casting if necessary
+          const columnFieldType = this.fieldTypes.filter(fieldType => fieldType.label === column);
+          const queryColumn = columnFieldType.length && columnFieldType[0].type === 'numeric'
```
Comment (ScopeyNZ) [inline client/src/lib/CKANApi/DataStore/Query.js]: What do you think about making this `type !== 'text'` (or whatever that type is).

Comment (robbieaverill) [reply client/src/lib/CKANApi/DataStore/Query.js]: Sure
