### PR TITLE
FIX Removed trim() null pointer error, and on integers

### LINKED ISSUE #131: Uncaught (in promise) TypeError: Cannot read property 'trim' of null
PresentedOptionsField:

```js
    const trimmed = options.map(item => item.trim().replace(/\s+/g, ' '));
```

When trying to use the presented options field in a dropdown filter.

### PR DESCRIPTION
**Pull request by robbieaverill**
Fixes #131

### CODE REVIEW

File: client/src/components/tests/CKANPresentedOptionsField-test.js [hunk 1]
```diff
@@ -50,43 +50,49 @@ const prepCKANApiMock = (options = null) => {
...
-    expect(options).toHaveLength(2);
-    const secondOption = options.at(1).render();
-    expect(secondOption.find('input').val()).toBe(SELECT_TYPE_CUSTOM);
-    expect(secondOption.find(':checked')).toHaveLength(1);
+      const options = component.find('.ckan-presented-options__option-group');
+      expect(options).toHaveLength(2);
+      const secondOption = options.at(1).render();
+      expect(secondOption.find('input').val()).toBe(SELECT_TYPE_CUSTOM);
+      expect(secondOption.find(':checked')).toHaveLength(1);
+    });
```
Comment (robbieaverill) [inline client/src/components/tests/CKANPresentedOptionsField-test.js]: These changes are all just indentation from wrapping it inside a `describe()` callback
