### PR TITLE
FIX Use the resource ID not the dataset ID, fixes broken initial save

### LINKED ISSUE #113: Adding a new dataset with the default resource results in an internal server error
Steps to reproduce:

* Create a new CKAN Registry Page
* Go the Data tab
* Enter `https://catalogue.data.govt.nz/dataset/directory-of-educational-institutions` into the Data source URL field
* Wait for the Resource name dropdown to populate with values
* Notice that the change tracker hasn't detected new changes (#112)
* Click "Saved"

Expected: columns should be populated

Actual: Internal Server Error toast message, backend response reports a 404 from the API

Workaround: change the default Resource name value to something else, save it, change it back again, save it again

### PR DESCRIPTION
**Pull request by robbieaverill**
Fixes #113

Also uses the correct version of react test utils to allow the build to work

### CODE REVIEW

File: client/src/components/CKANResourceLocatorField.js [hunk 1]
```diff
@@ -210,7 +210,7 @@ class CKANResourceLocatorField extends Component {
         // a value for the user. This will just be the first datastore_active resource in the list
         if (!spec.resource && dataset) {
           const resource = dataset.resources.find(res => res.datastore_active);
-          spec.resource = resource && resource.package_id;
+          spec.resource = resource && resource.id;
```
Comment (robbieaverill) [inline client/src/components/CKANResourceLocatorField.js]: This is the fix - the rest is auxiliary
