### PR TITLE
FIX Updating GridFieldDetailForm saving of ResourceFields to not create invalid ordering when updating the order field

### LINKED ISSUE #98: Improve column Presented Order option
Currently (`1.0.x-dev`) updating the Presented Order in a column edit screen will not alter the order of other columns.

This creates duplicate ordering (i.e moving to '7' would mean there are now 2 columns with the order '7'.) This is okay if the user is looking for _relative ordering_, but it's not doing a full reorder it a way that will always make sense.

- [ ] At minimum, we should update the label from 'Presented Order' to 'Relative Order'
- [ ] Stretch goal: Add a reordering function on Save that reorders all columns based on any change made.

### PR DESCRIPTION
**Pull request by ScopeyNZ**
WIP because I need to add some tests but the functionality is ready for a peer review and test. It'd be nice for someone to check this out and play with it a bit because I was trying to get this done before bug day was over :laughing:

This overloads the save handler for ResourceField so that we can implement our own logic that updates other ResourceField after a sort order is updated. I chose this over creating an extension because an extension would apply to all GridFieldDetailForm's.

Fixes #98

### CODE REVIEW

File: src/Model/ResourceField.php [hunk 1]
```diff
@@ -13,7 +13,7 @@
  * Represents a generic field on a CKAN Resource, e.g. a column in a spreadsheet.
  * It is intentionally generic, as the resource may not be a tabular one, e.g. geospatial data to be rendered in a map.
  *
- * @method Resource Resource
+ * @property Resource Resource
```
Comment (NightJar) [inline src/Model/ResourceField.php]: Is a property _and_ a method though... more commonly accessed as a method.

**Comment by NightJar** [comment]
Is this still WIP?

**Comment by NightJar** [comment]
Apparently no longer WIP :)
